// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Examination", b =>
                {
                    b.Property<Guid>("ExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("examination_id");

                    b.Property<int>("BeforeTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("before_time_minutes");

                    b.Property<DateTime>("CreatedDay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_day");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ExaminationCode")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("examination_code");

                    b.Property<string>("ExaminationType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("examination_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedDay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_day");

                    b.HasKey("ExaminationId");

                    b.HasIndex("ExaminationCode")
                        .IsUnique();

                    b.HasIndex("SemesterId");

                    b.ToTable("examinations");
                });

            modelBuilder.Entity("Domain.Entities.GradingDiary", b =>
                {
                    b.Property<Guid>("GradingDiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("grading_diary_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("examination_code");

                    b.Property<Guid>("CreateById")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("PaperSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("paper_set_id");

                    b.HasKey("GradingDiaryId");

                    b.HasIndex("CreateById");

                    b.HasIndex("PaperSetId")
                        .IsUnique();

                    b.ToTable("grading_diary");
                });

            modelBuilder.Entity("Domain.Entities.PaperSet", b =>
                {
                    b.Property<Guid>("PaperSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("paper_set_id");

                    b.Property<Guid>("CreateById")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ExaminationId")
                        .HasColumnType("uuid")
                        .HasColumnName("examination_id");

                    b.Property<string>("FileAnswerRubric")
                        .HasColumnType("text")
                        .HasColumnName("file_answer_rubric");

                    b.Property<string>("FileAnswerTemplate")
                        .HasColumnType("text")
                        .HasColumnName("file_answer_template");

                    b.Property<string>("FileQuestionDocs")
                        .HasColumnType("text")
                        .HasColumnName("file_question_docs");

                    b.Property<int>("FileType")
                        .HasColumnType("integer")
                        .HasColumnName("file_examination_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PaperSetCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("paper_set_code");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("integer")
                        .HasColumnName("total_questions");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("PaperSetId");

                    b.HasIndex("CreateById");

                    b.HasIndex("ExaminationId");

                    b.HasIndex("SemesterId");

                    b.ToTable("paper_sets");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedDay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_day");

                    b.Property<Guid>("PaperSetId")
                        .HasColumnType("uuid")
                        .HasColumnName("paper_set_id");

                    b.Property<decimal>("Point")
                        .HasColumnType("numeric")
                        .HasColumnName("point");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Title");

                    b.Property<DateTime>("UpdatedDay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_day");

                    b.HasKey("QuestionId");

                    b.HasIndex("PaperSetId");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("Domain.Entities.Semester", b =>
                {
                    b.Property<Guid>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<DateTime>("CreatedDay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_day");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SemesterCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("semester_code");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedDay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_day");

                    b.HasKey("SemesterId");

                    b.HasIndex("SemesterCode")
                        .IsUnique();

                    b.ToTable("semesters");
                });

            modelBuilder.Entity("Domain.Entities.StudentExamination", b =>
                {
                    b.Property<Guid>("StudentExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("student_examination_id");

                    b.Property<DateTime>("CreatedDay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_day");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uuid")
                        .HasColumnName("exam_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UpdatedDay")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_day");

                    b.HasKey("StudentExaminationId");

                    b.HasIndex("ExamId");

                    b.HasIndex("StudentId");

                    b.ToTable("student_examination");
                });

            modelBuilder.Entity("Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<string>("AiLogs")
                        .HasColumnType("text")
                        .HasColumnName("ai_logs");

                    b.Property<decimal?>("AiScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ai_score");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<Guid>("DiaryId")
                        .HasColumnType("uuid")
                        .HasColumnName("diary_id");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_path");

                    b.Property<decimal?>("LecturerScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("lecturer_score");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentExaminationId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_examination_id");

                    b.Property<string>("SubmissionFile")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("submission_name");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("SubmissionId");

                    b.HasIndex("DiaryId");

                    b.HasIndex("StudentExaminationId");

                    b.ToTable("student_submission");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Lecturer", b =>
                {
                    b.HasBaseType("Domain.Entities.User");

                    b.Property<string>("LecturerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lecturer_code");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.ToTable("lecturers");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.HasBaseType("Domain.Entities.User");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("major");

                    b.Property<string>("StundentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("student_code");

                    b.ToTable("students");
                });

            modelBuilder.Entity("Domain.Entities.Examination", b =>
                {
                    b.HasOne("Domain.Entities.Semester", "Semester")
                        .WithMany("Examinations")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Domain.Entities.GradingDiary", b =>
                {
                    b.HasOne("Domain.Entities.Lecturer", "CreatedBy")
                        .WithMany("GradingDiaries")
                        .HasForeignKey("CreateById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.PaperSet", "PaperSet")
                        .WithOne("GradingDiary")
                        .HasForeignKey("Domain.Entities.GradingDiary", "PaperSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("PaperSet");
                });

            modelBuilder.Entity("Domain.Entities.PaperSet", b =>
                {
                    b.HasOne("Domain.Entities.Lecturer", "CreateBy")
                        .WithMany("PaperSetsCreated")
                        .HasForeignKey("CreateById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Examination", "Examination")
                        .WithMany("PaperSets")
                        .HasForeignKey("ExaminationId");

                    b.HasOne("Domain.Entities.Semester", "Semester")
                        .WithMany("PaperSets")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateBy");

                    b.Navigation("Examination");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Domain.Entities.Question", b =>
                {
                    b.HasOne("Domain.Entities.PaperSet", "PaperSet")
                        .WithMany("Questions")
                        .HasForeignKey("PaperSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaperSet");
                });

            modelBuilder.Entity("Domain.Entities.StudentExamination", b =>
                {
                    b.HasOne("Domain.Entities.Examination", "Examination")
                        .WithMany("StudentExaminations")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Student", "Student")
                        .WithMany("StudentExaminations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Examination");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Entities.Submission", b =>
                {
                    b.HasOne("Domain.Entities.GradingDiary", "GradingDiary")
                        .WithMany("Submissions")
                        .HasForeignKey("DiaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.StudentExamination", "StudentExamination")
                        .WithMany()
                        .HasForeignKey("StudentExaminationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradingDiary");

                    b.Navigation("StudentExamination");
                });

            modelBuilder.Entity("Domain.Entities.Lecturer", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Lecturer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.HasOne("Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("Domain.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Examination", b =>
                {
                    b.Navigation("PaperSets");

                    b.Navigation("StudentExaminations");
                });

            modelBuilder.Entity("Domain.Entities.GradingDiary", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Domain.Entities.PaperSet", b =>
                {
                    b.Navigation("GradingDiary");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entities.Semester", b =>
                {
                    b.Navigation("Examinations");

                    b.Navigation("PaperSets");
                });

            modelBuilder.Entity("Domain.Entities.Lecturer", b =>
                {
                    b.Navigation("GradingDiaries");

                    b.Navigation("PaperSetsCreated");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Navigation("StudentExaminations");
                });
#pragma warning restore 612, 618
        }
    }
}
