// <auto-generated />
using System;
using AI_Assisted_SWR_Grading_System.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AI_Assisted_SWR_Grading_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908122330_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.ExamMaterial", b =>
                {
                    b.Property<Guid>("ExamMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreateById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExamMaterialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ExaminationId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileAnswerTemplate")
                        .HasColumnType("text");

                    b.Property<string>("FileDocs")
                        .HasColumnType("text");

                    b.Property<string>("FileRubric")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ExamMaterialId");

                    b.HasIndex("CreateById");

                    b.HasIndex("ExaminationId");

                    b.ToTable("ExamMaterials");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Examination", b =>
                {
                    b.Property<Guid>("ExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BeforeTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ExaminationCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("ExaminationId");

                    b.HasIndex("SemesterId");

                    b.ToTable("Examinations");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Grading", b =>
                {
                    b.Property<Guid>("GradingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiLogs")
                        .HasColumnType("text");

                    b.Property<decimal?>("AiScore")
                        .HasColumnType("numeric");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("numeric");

                    b.Property<string>("GradingCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("LecturerScore")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GradingId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("Gradings");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Semester", b =>
                {
                    b.Property<Guid>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SemesterCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("SemesterId");

                    b.ToTable("Semesters");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SubmissionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SubmissionId");

                    b.HasIndex("LecturerId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Lecturer", b =>
                {
                    b.HasBaseType("AI_Assisted_SWR_Grading_System.Domain.Entities.User");

                    b.Property<string>("LecturerCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Lecturer");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Student", b =>
                {
                    b.HasBaseType("AI_Assisted_SWR_Grading_System.Domain.Entities.User");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StundentCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.ExamMaterial", b =>
                {
                    b.HasOne("AI_Assisted_SWR_Grading_System.Domain.Entities.Lecturer", "CreateBy")
                        .WithMany("ExamMaterialsCreated")
                        .HasForeignKey("CreateById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI_Assisted_SWR_Grading_System.Domain.Entities.Examination", "Examination")
                        .WithMany("ExamMaterials")
                        .HasForeignKey("ExaminationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateBy");

                    b.Navigation("Examination");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Examination", b =>
                {
                    b.HasOne("AI_Assisted_SWR_Grading_System.Domain.Entities.Semester", "Semester")
                        .WithMany("Examinations")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Grading", b =>
                {
                    b.HasOne("AI_Assisted_SWR_Grading_System.Domain.Entities.Submission", "Submission")
                        .WithMany("Gradings")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Submission", b =>
                {
                    b.HasOne("AI_Assisted_SWR_Grading_System.Domain.Entities.Lecturer", "Lecturer")
                        .WithMany("Submissions")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Examination", b =>
                {
                    b.Navigation("ExamMaterials");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Semester", b =>
                {
                    b.Navigation("Examinations");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Submission", b =>
                {
                    b.Navigation("Gradings");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Lecturer", b =>
                {
                    b.Navigation("ExamMaterialsCreated");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
