// <auto-generated />
using System;
using AI_Assisted_SWR_Grading_System.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AI_Assisted_SWR_Grading_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909140138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.ExamMaterial", b =>
                {
                    b.Property<Guid>("ExamMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("exam_material_id");

                    b.Property<Guid>("CreateById")
                        .HasColumnType("uuid")
                        .HasColumnName("create_by_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("ExamMaterialCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("exam_material_code");

                    b.Property<Guid>("ExaminationId")
                        .HasColumnType("uuid")
                        .HasColumnName("examination_id");

                    b.Property<string>("FileAnswerRubric")
                        .HasColumnType("text")
                        .HasColumnName("file_answer_rubric");

                    b.Property<string>("FileAnswerTemplate")
                        .HasColumnType("text")
                        .HasColumnName("file_answer_template");

                    b.Property<string>("FileQuestionDocs")
                        .HasColumnType("text")
                        .HasColumnName("file_question_docs");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("ExamMaterialId");

                    b.HasIndex("CreateById");

                    b.HasIndex("ExaminationId");

                    b.ToTable("exam_materials");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Examination", b =>
                {
                    b.Property<Guid>("ExaminationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("examination_id");

                    b.Property<int>("BeforeTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("before_time_minutes");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<string>("ExaminationCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("examination_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<Guid>("SemesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("ExaminationId");

                    b.HasIndex("SemesterId");

                    b.ToTable("examinations");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Grading", b =>
                {
                    b.Property<Guid>("GradingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("grading_id");

                    b.Property<string>("AiLogs")
                        .HasColumnType("text")
                        .HasColumnName("ai_logs");

                    b.Property<decimal?>("AiScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ai_score");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("create_date");

                    b.Property<decimal?>("FinalScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("final_score");

                    b.Property<string>("GradingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grading_code");

                    b.Property<decimal?>("LecturerScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("lecturer_score");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date");

                    b.HasKey("GradingId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("gradings");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Semester", b =>
                {
                    b.Property<Guid>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("semester_id");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("SemesterCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("semester_code");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("SemesterId");

                    b.HasIndex("SemesterCode")
                        .IsUnique();

                    b.ToTable("semesters");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_date");

                    b.Property<string>("Folder")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("folder");

                    b.Property<Guid>("LecturerId")
                        .HasColumnType("uuid")
                        .HasColumnName("lecturer_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("SubmissionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("submission_name");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_date");

                    b.HasKey("SubmissionId");

                    b.HasIndex("LecturerId");

                    b.ToTable("submissions");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("date")
                        .HasColumnName("birthday");

                    b.Property<string>("Cccd")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cccd");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Lecturer", b =>
                {
                    b.HasBaseType("AI_Assisted_SWR_Grading_System.Domain.Entities.User");

                    b.Property<string>("LecturerCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lecturer_code");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.ToTable("users");

                    b.HasDiscriminator().HasValue("Lecturer");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Student", b =>
                {
                    b.HasBaseType("AI_Assisted_SWR_Grading_System.Domain.Entities.User");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("major");

                    b.Property<string>("StundentCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("student_code");

                    b.ToTable("users");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.ExamMaterial", b =>
                {
                    b.HasOne("AI_Assisted_SWR_Grading_System.Domain.Entities.Lecturer", "CreateBy")
                        .WithMany("ExamMaterialsCreated")
                        .HasForeignKey("CreateById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AI_Assisted_SWR_Grading_System.Domain.Entities.Examination", "Examination")
                        .WithMany("ExamMaterials")
                        .HasForeignKey("ExaminationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreateBy");

                    b.Navigation("Examination");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Examination", b =>
                {
                    b.HasOne("AI_Assisted_SWR_Grading_System.Domain.Entities.Semester", "Semester")
                        .WithMany("Examinations")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Grading", b =>
                {
                    b.HasOne("AI_Assisted_SWR_Grading_System.Domain.Entities.Submission", "Submission")
                        .WithMany("Gradings")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Submission", b =>
                {
                    b.HasOne("AI_Assisted_SWR_Grading_System.Domain.Entities.Lecturer", "Lecturer")
                        .WithMany("Submissions")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Examination", b =>
                {
                    b.Navigation("ExamMaterials");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Semester", b =>
                {
                    b.Navigation("Examinations");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Submission", b =>
                {
                    b.Navigation("Gradings");
                });

            modelBuilder.Entity("AI_Assisted_SWR_Grading_System.Domain.Entities.Lecturer", b =>
                {
                    b.Navigation("ExamMaterialsCreated");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
